from fastapi import Depends, HTTPException, status, APIRouter, Response
from fastapi.security import OAuth2PasswordRequestForm
from sqlalchemy.orm import Session
from core.database import get_db
from core import schemas
from core.models import user_model
from ..utils import hashing
from OAuth2 import OAuth2
from core.config import jwt_settings
from sqlalchemy.exc import IntegrityError


router = APIRouter(
    prefix="/auth",
    tags=["auth"],
)

@router.post("/register", status_code=status.HTTP_201_CREATED, response_model=schemas.UserOut)
def create_user(user_data: schemas.UserRegister,response: Response, db: Session = Depends(get_db)): # user_data is converted to pydantic object from json by fastapi itself if we specify a pydantic schema

    user_data.password = hashing.hash_password(user_data.password)  # Hash the password before storing it
    new_user = user_model.User(**user_data.model_dump()) #model_dump() will convert to dict and unload each field first_name=user_data.first_name,last_name=user_data.last_name,email=user_data.email,password=user_data.password
        # we are using models to add data in db using pydantic object
    try:
        db.add(new_user)
        db.commit()
        db.refresh(new_user)# here our new_user object will be updated with the id generated by the database after commit and also any other default values set by the database
    except IntegrityError:
        db.rollback()
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="User already exists")

    access_token = OAuth2.create_access_token(data={"id": new_user.id, 'first_name': new_user.first_name})

    response.set_cookie( # response is used to modify http headers and give custom inst
        key="access_token", # by this key name it will be stored in browser
        value=access_token,
        httponly=True,  # anti xss
        max_age=jwt_settings.ACCESS_TOKEN_EXPIRE_MINUTES*60,  # 24hrs
        samesite="lax",  # CSRF protection
        secure=True  # allow local non-HTTPS monolithic hosting
    )

    return new_user # here we will return response as per the response_model to avoid releasing any credentials


@router.post("/login", response_model=schemas.UserOut)
def login_user(response: Response, user_credentials: OAuth2PasswordRequestForm = Depends(), db: Session = Depends(get_db)):
# OAuth2PasswordRequestForm = Depends() this is a special class provided by fastapi which will automatically parse the form data sent by the client and convert it into an object of type OAuth2PasswordRequestForm which has two attributes username and password
# if depends() is empty it means it will go back and check class here it is OAuth2PasswordRequestForm and it understands that dependency is OAuth2PasswordRequestForm here
    user_data = db.query(user_model.User).filter(user_model.User.email == user_credentials.username).first()

    if not user_data or not hashing.verify_password(user_credentials.password, user_data.password):
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Incorrect username or password")

    access_token = OAuth2.create_access_token(data={"id": user_data.id, 'first_name':user_data.first_name})

    response.set_cookie( # response is used to modify http headers and give custom inst
        key="access_token", # by this key name it will be stored in browser
        value=access_token,
        httponly=True,  # anti xss
        max_age=jwt_settings.ACCESS_TOKEN_EXPIRE_MINUTES*60,  # 24hrs
        samesite="lax",  # CSRF protection
        secure=True  # allow local non-HTTPS monolithic hosting
    )
    # we need response: Response to modify the headers. we need to modify headers to send browser instructions

    return user_data

# we do not return any render-template as we send data and we send a status code. If we do not send explicitly a status code fastapi sends 200ok automatically which goes to react frontend
# then react frontend sees data and status_code and knows we can render login page or not based on the status code and data received. if we send 201 created then react frontend will know that user is created and can render login page. if we send 400 bad request then react frontend will know that user already exists and can show error message on registration page itself

@router.post("/logout", status_code=status.HTTP_200_OK)
def logout_user(response: Response):
    response.delete_cookie(
        key="access_token",
        httponly=True,
        samesite="lax",
        secure=True
    )
    return {"message": "Successfully logged out"}





